services:
  database:
    container_name: todo-database
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_DB}'"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - network
    profiles:
      - backend
      - deploy

  backend:
    container_name: bookstore-backend
    image: ${REGISTRY}/backend:lastest
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      DATABASE_DB: ${DATABASE_DB}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_HOST: database
    depends_on:
      database:
        condition: service_healthy
    networks:
      - network
    profiles:
      - backend
      - deploy

volumes:
  database:
    name: bookstore-database
    external: true
networks:
  network:
    name: bookstore-network
    external: true
